### PR TITLE
Added missing types into SynType and fixed the sample code

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
While working on [Hawaii](https://github.com/Zaid-Ajaj/Hawaii), I found myself defining these extensions myself so I thought it would be better to include them here instead :)

### CODE REVIEW

**Comment by 7sharp9** [comment]
Looks great thanks!

**Comment by Zaid-Ajaj** [comment]
Thanks for merging! Any chance you could publish a new package with these additions? 🙏

**Comment by 7sharp9** [comment]
Unfortunately that above my pay grade.

**Comment by Zaid-Ajaj** [comment]
> Unfortunately that above my pay grade.

Understandable 👍 thanks the quick response

**Comment by 7sharp9** [comment]
I think only @Krzysztof-Cieslak has the key.

**Comment by Krzysztof-Cieslak** [comment]
Released in `0.8.0`

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @Krzysztof-Cieslak ❤️

**Pull request merged**
