### PR TITLE
Add DSL conviencies for attributes, XML docs and syntactic record fields

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
While on the stream, I had to build many of those and I wished they were built-in so here they are :smile:

### CODE REVIEW

**Comment by Krzysztof-Cieslak** [comment]
Awesome, thanks

**Comment by 7sharp9** [comment]
@Zaid-Ajaj You forgot to update the docs!  :-)

**Comment by Zaid-Ajaj** [comment]
@7sharp9 docs for the helpers you mean?

**Comment by Zaid-Ajaj** [comment]
@Krzysztof-Cieslak Can you please publish a version with these included helpers when you have time?  thanks a lot :pray:

**Comment by Krzysztof-Cieslak** [comment]
`0.4.0` released - should be online after NuGet.org is done with all its magic

**Pull request merged**
