### PR TITLE
Update to latest Fantomas and FCS 34.1

### PR DESCRIPTION
**Pull request by Krzysztof-Cieslak**
Updates FsAST to Fantomas 3.3.0 and FCS 34.1 (latest supported by Fantomas)

### CODE REVIEW

**Review by ctaggart — APPROVED** [review]
Thanks! Changes look great. I'm not really maintaining this. Is there a good place I can transfer it?

**Comment by Krzysztof-Cieslak** [comment]
I can take over - I'll probably need the library for a couple of tooling ideas I have - so we can move it to Ionide org.

Or otherwise, fsprojects is always a good place for projects.

**Comment by ctaggart** [comment]
I published this as https://www.nuget.org/packages/FsAst/0.2.0. Ionide sounds good.

**Comment by Krzysztof-Cieslak** [comment]
> I published this...

Awesome, thanks a lot ❤️ 

> Ionide sounds good.

Cool, so just transfer it to `ionide` org... and I guess, I'll also need NuGet release rights

**Comment by ctaggart** [comment]
I don't have permission to transfer it directly to Ionide.
image

I could transfer it to you and you could transfer it in or you could give me permission.

**Comment by Krzysztof-Cieslak** [comment]
I've sent you an invite to Iondie org, it should give you the right to create repos (so to move it)

**Comment by Krzysztof-Cieslak** [comment]
Awesome, it seems everything is fine. Thanks.

And thanks a lot for creating and working on this project! It's great and I hope I'll be able to move it forward :)

**Comment by ctaggart** [comment]
Thank you for providing a new home for it and carrying it forward!

**Pull request merged**
